[project]
name = 'Tokenized-Commercial-Solar-Project-Financing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.investment-management]
path = 'contracts/investment-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.production-monitoring]
path = 'contracts/production-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-verification]
path = 'contracts/project-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.revenue-distribution]
path = 'contracts/revenue-distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
